language: python

matrix:
  include:
    - sudo: required
      services: docker
      env: RELEASE=trusty
    - sudo: required
      env: RELEASE=precise

env:
  global:
  - ALIAS=nightly

install:
- pushd /opt/pyenv/
- sudo git checkout master
- sudo git pull
- popd
- python -m pip install "virtualenv==15.0.2"
- python -m virtualenv --version

before_script:
- 'export INSTALL_DEST=${INSTALL_DEST:-/opt/python}'
- 'export LSB_RELEASE=${LSB_RELEASE:-$(lsb_release -rs || echo ${$(sw_vers -productVersion)%*.*})}'
- 'export OS_NAME=${OS_NAME:-$(lsb_release -is | tr "A-Z" "a-z" || echo "osx")}'
- 'export ARCH=${ARCH:-$(uname -m)}'
- 'export PACKAGES=${PACKAGES:-pip nose pytest mock wheel}'
- 'export CPYTHON_ONLY_PKGS="numpy"'
- export PYTHON_COFIGURE_OPTS="$CONFIGURE_OPTS --enable-unicode=ucs4"

script: ./bin/compile

after_success: ./bin/archive

after_failure: cat /tmp/python-build.*.log

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
